# Set the base image to node
FROM node:7

MAINTAINER Max Campbell <maxc@maxc.in>

# install nodemon
RUN npm install nodemon -g

# import the rest
WORKDIR /app
ADD . /app
RUN npm install


# Expose port
EXPOSE  3000

# Run app using npm
CMD ["npm", "run","development"]

