# Set the base image to node
FROM node:7

MAINTAINER Max Campbell <maxc@maxc.in>

# install nodemon and mocha
RUN npm install nodemon mocha -g

# import the application into the app folder
WORKDIR /app
ADD . /app
#install the application
RUN npm install

# Expose port
EXPOSE  3000

# Run app using npm
CMD ["npm", "run","development"]

