# Set the base image to node
FROM rethinkdb:latest

MAINTAINER Max Campbell <maxc@maxc.in>

#install netcat
RUN apt-get update
RUN apt-get install -y netcat
# Run the database
CMD ["rethinkdb", "--bind", "all"]